### PR TITLE
Allow end-users (or roles anyway) to reject default plugin repositories and features

### PR DESCRIPTION
**Pull request by lonniev**
Due to the design of chef attribute precedence specifically when dealing with hashes, there is no chef-way to enable a role to reject entirely the attributes set in the recipe files. One can change the values of the keys but one can't drop a key.

This change introduces an "excluding" array into the eclipse property set. The role can include a key from the plugins hash in the excluding array and then the recipe will reject any such keys from the plugins hash.

If there is a better chef or better ruby way to do this, please advise.

### CODE REVIEW

**Comment by ap1kenobi** [comment]
Wouldn't it be easier to leave the plugin hash empty and simply add items to it from your role/node?

**Comment by lonniev** [comment]
@ap1kenobi I think you are asking if it would be better if the default recipe provided no attributes (default, override, etc) and left it all to the user's roles to configure. If so, I agree--in theory.

In practice, it is very pedagogic if a recipe author provides a set of attributes that illustrate how the recipe should work or which make the recipe "smart enough" to do something useful when the user provides no configuration in their environments or roles. So, providing some attributes in the recipe is a good thing.

The challenge here is that the technique adopted by the Chef community for merging hashes does not support a "reject" capability at all: it offers only Set Union or Set Replacement but not Set Subtraction. In order to gain the ability to reject the original author's choice of repositories and plugins, one has to refactor that original recipe to explicitly reject hashes that the end roles or environments specify.

My branch of this recipe now does more including this rejection of unwanted plugins: it skips installing features that appear to already be installed, it makes the whole eclipse area a+rw accessible (so that users can update Eclipse without having to sudo eclipse &, and it installs a bunch of webkit cruft that Ubuntu inconveniently leaves out.

I wouldn't pull my PR into the default recipe here anymore but just take a look at the wacky stuff I am doing to make this more useful. (Also, it would be good to get vagrant-cachier to support "ark" so that we'd save the long overhead of pulling down eclipse tar.gz files each provisioning run.)

**Comment by ap1kenobi** [comment]
@lonniev, I wasn't questioning usefulness of your other additions although I do think you should put them into a separate PR since they have nothing to do with the original issue you were trying to address.  For simplicity sake, however, you _could_ ask the author of this cookbook to remove entries from the plugins hash to make it overridable.  Frankly, I think eclipse plugins deserve their own cookbook or this whole thing should be ported into a LWRP similarly to PHP one so that recipes are easier to construct.

**Comment by lonniev** [comment]
That's all good advice. At the time, I needed an immediate solution, didn't know what I really would need, wasn't in a position to try to explain and negotiate a solution, and knew enough to hack my way to something that works.

—Lonnie VanZandt

303-900-3048

**Comment by lonniev** [comment]
obsolete due to the passage of Time.

**Pull request closed without merging**
